### ISSUE TITLE
Strange behavior when loading data from a column with "space" in column header

### ISSUE THREAD

**Issue by pchanas** [kyushy/kibana-xlsx-import#13]
Loading a 3 column xlsx file, 
column 1 : "date" (date)
column 2 : "downloads" (integer)
column 3 : 'daily downloads' (integer)

I chose date for c1 mapping, double (or float in an other test) for c2 et c3.
Data is loaded:

      {
        "_index": "myindex",
        "_type": "doc",
        "_id": "0eg3K2MBlI2vUD8Ex95q",
        "_score": 1,
        "_source": {
          "date": "2015-01-11",
          "downloads": "503",
          "daily downloads": "53"
        }
      },

But when I create the kibana index I get the following fields:

daily downloads | string 
daily downloads.keyword | string
daily_downloads | number

Then in the vizualusations, I can only use "daily_downloads" as numerical field but this field is null...
By removing the " " in the column header, everything is fine.

**Comment by kyushy** [comment]
fixed in https://github.com/kyushy/kibana-xlsx-import/commit/6eb90a58d77032f6cc75f4d3aafb07d637e6269d

thanks for the feed back
